# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
     import_workflow:
         class: AppBundle\Service\ImportWorkflowService\ImportWorkflow
         autowire: true
     validator:
         class: AppBundle\Service\ValidatorService\ValidatorService
         autowire: true
     rules_filter:
         class: AppBundle\Service\RulesService\RulesService
         autowire: true
     create_product:
         class: AppBundle\Service\CreateProductService\CreateProductService
         autowire: true
